#!/usr/bin/env node

// Imports
const parseGitConfig = require('parse-git-config');
const git = require('git-rev-sync');
const axios = require('axios');
const chalk = require('chalk');
const inquirer = require('inquirer');


// Variable Setup
// Shortcut for chalk logging
const log = console.log;
// username to use for absolute path to global .gitconfig file
const osUsername = require("os").userInfo().username;
// Parses global .gitconfig file
const gitConfig = parseGitConfig.sync({
	path: `/Users/${osUsername}/.gitconfig`,
});
// Sets up JIRA related variables
const jira = {
	"self": gitConfig.jira.username,
	"key": gitConfig.jira.key,
	"inProgressId": 21,
	"toDoId": 10000,
	"relatedIssueId": 10003,
};
// Gets current branch name
// const currentBranch = git.branch();
const currentBranch = 'REH-332';
// Boolean to determine if current branch is a Jira Task
const isJiraTask = !!currentBranch.split("").reverse().join("").match(RegExp(/\d+-[A-Z]+(?!-?[a-zA-Z]{1,10})/));
// Axios instance for pinging the JIRA API
const jiraAPI = axios.create({
	baseURL: 'https://recoverybrands.atlassian.net/rest/api/2',
	headers: {'Authorization': `Basic ${jira.key}`},
});

const getRelatedIssueChoices = (linkedIssues) => {

	let relatedIssuesChoices = linkedIssues.reduce((filteredData, linkedIssue) => {
		let direction = !!linkedIssue.inwardIssue ? 'inwardIssue' : 'outwardIssue';

		if ((parseInt(linkedIssue.type.id) === jira.relatedIssueId) &&
			(parseInt(linkedIssue[direction].fields.status.id) === jira.toDoId)) {

				let taskId = linkedIssue[direction].key;
				let taskTitle = linkedIssue[direction].fields.summary;

				filteredData.push({
					name: `[${taskId}] - ${taskTitle}`,
					value: taskId,
				});
		}
		return filteredData;

	}, []);

	return relatedIssuesChoices;
};

const setInProgress = (taskId = currentBranch) => {
	return jiraAPI.post(`/issue/${taskId}/transitions`, {
		"transition": {
			"id": jira.inProgressId,
		}
	})
	.then(response => {
		if (response.status !== 204) {
			log(chalk.red(`API Error. ${taskId} status not changed.`))
		} else {
			log(chalk.green(`${taskId} Changed to 'In Progress'`));
		}

		return assignTaskToSelf(taskId);
	});
};

const getTaskInfo = (taskId = currentBranch) => {
	return jiraAPI.get(`/issue/${taskId}/?fields=status,issuelinks,summary`);

};

const assignTaskToSelf = (taskId) => {
	return jiraAPI.put(`/issue/${taskId}/assignee`, {
		"name": jira.self,
	})
	.then(response => {
		if (response.status !== 204) {
			log(chalk.red(`API Error. ${taskId} not assigned to you.`))
		} else {
			log(chalk.green(`${taskId} assigned to you.`));
		}

		return;
	});
};

const relatedIssuePrompt = (choices) => {

	if (choices.length) {
		return inquirer.prompt([
			{
				type: 'checkbox',
				name: 'tasks',
				message: `The following tasks are related to ${currentBranch} and have not been started.\nSelect the items you'd like to switch to "In Progress".\n`,
				choices: choices
			}
		]);
	} else {
		return {"tasks": []};
	}
};

if (!isJiraTask) {
	log(chalk.bold('Not a JIRA Task Branch'));
	return;
}

log(chalk.bold('JIRA Task Branch'));

getTaskInfo()
.then((response) => {
	const relatedIssueChoices = getRelatedIssueChoices(response.data.fields.issuelinks);
	const isTaskToDo = parseInt(response.data.fields.status.id) === jira.toDoId;
	const maybeInProgress = isTaskToDo ? setInProgress() : false

	if (!isTaskToDo) {
		log(chalk.dim(`${currentBranch} was not "To Do". Leaving status unchanged.`));
	}

	return Promise.all([
		maybeInProgress,
		relatedIssueChoices
	]);

})
.then(response => {
	const relatedIssuesChoices = response[1];
	return relatedIssuePrompt(relatedIssuesChoices)
})
.then(function (response) {
	const tasksToChange = response.tasks;
	const tasksToChangePromises = [];

	tasksToChange.forEach((task) => {
		tasksToChangePromises.push(setInProgress(task));
	});

	return Promise.all(tasksToChangePromises);
})
.catch(e => console.log(e));
